### ISSUE TITLE
serial port detection error

### ISSUE THREAD

**Issue by isthiscash** [RuudMulder/SerialMidiBridge#1]
When I use the "ScanPorts" function, it does scan the correct serial port from my uno. However after selecting the correct baudrate, serial to MIDI and MIDI to serial parameters, I get an error message that says "Serial Port Opening Error"

just curious if there's a specific reason for this error and if there's a workaround.

**Comment by RuudMulder** [comment]
I'm sorry, but I can't reproduce the error, but it seems to be an error of pyserial.
The app is only a GUI version of the script https://github.com/raspy135/serialmidi and both just return whatever pyserial gives on opening the port.
Maybe you can try the script or debug to find more about the error?

**Comment by Grumpy-Mike** [comment]
I turned to this because I can't get serialmidi to work on my iMac M1 running Sonoma 14.2. With your interface I get a "can't run because IAC Driver Bus 1 is not on the list" error.
With the serialmidi code I get an 
INFO:root:IN :  ''
INFO:root:OUT : ''
message.

Sadly my message has not had a response on the serialmidi Github.  

Also the scan button sometimes needs several prods to get it to scan anything. When it does it comes up with /dev/cu.usbmodem24101 where as to use serialmidi  to read the input I need to use /dev/tty.usbmodem24101.

**Comment by RuudMulder** [comment]
Hi Mike,

I do not have an M1, so unfortunately I cannot test your problem. As stated, the SerialMidiBridge is just a GUI for serialmidi. So if serialmidi doesn't work the GUI won't either.
Serialmidi uses rtmidi (https://github.com/thestk/rtmidi) to detect the serial ports. Maybe it can't find your port because the badrate is not set correctly?
Also, did you add a port to the IAC Driver in Audio/MIDI Setup? It needs a virtual MIDI port on the Mac to work.

Kind regards,
Ruud

**Comment by Grumpy-Mike** [comment]
"Also, did you add a port to the IAC Driver in Audio/MIDI Setup?"

That was it! Thanks it has now sprung into life. Brilliant, best Christmas present ever. It means I can now update my book
[Arduino Music](http://www.apress.com/9781484217207)
Without rewriting a lot of projects.
Thanks again, and have a good Christmas yourself.

**Comment by RuudMulder** [comment]
Great! i'm glad you got it working. Have a good Christmas too.
Looks like a nice boot, by the way.
